[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = .
norecursedirs = .git
addopts =
    --strict
    -p no:homeassistant
    --timeout=20
    --timeout-method=thread
    --cov=custom_components
